ALTER TABLE productos ADD COLUMN IF NOT EXISTS marca VARCHAR(100);
ALTER TABLE productos ADD COLUMN IF NOT EXISTS modelo VARCHAR(120);
ALTER TABLE productos ADD COLUMN IF NOT EXISTS color VARCHAR(80);
ALTER TABLE productos ADD COLUMN IF NOT EXISTS material VARCHAR(120);
ALTER TABLE productos ADD COLUMN IF NOT EXISTS talla VARCHAR(80);
ALTER TABLE productos ADD COLUMN IF NOT EXISTS garantia VARCHAR(120);
ALTER TABLE productos ADD COLUMN IF NOT EXISTS condicion VARCHAR(80);
ALTER TABLE productos ADD COLUMN IF NOT EXISTS detalles_adicionales TEXT;

ALTER TABLE productos ADD COLUMN IF NOT EXISTS imagenes TEXT;

UPDATE productos
SET imagenes = imagen
WHERE (imagenes IS NULL OR imagenes = '')
  AND imagen IS NOT NULL
  AND imagen <> '';
